version: '3'
services:
    webfrontend:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8081:3000"
        volumes:
            - /app/node_modules
            - .:/app
    webtests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["yarn", "test"]
