version: '3'
services:
    webfrontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8081:3000"
        volumes:
            - /app/node_modules
            - .:/app
